"use client";

import { AnimatePresence, motion } from "motion/react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState, useTransition } from "react";
import { Bell, Check } from "lucide-react";

import { listNotifications, markAllRead, markRead } from "@/app/notifications/actions";
import { formatShortDate } from "@/lib/format";
import { cn } from "@/lib/utils";

interface Note {
  id: string;
  kind: string;
  title: string;
  body: string | null;
  href: string | null;
  readAt: Date | string | null;
  createdAt: Date | string;
}

/**
 * The bell. Notifications are generated by a sweep, so this only reads —
 * opening it fetches the current list rather than holding a stale one from
 * page load.
 */
export function NotificationBell({
  initialUnread,
  collapsed,
}: {
  initialUnread: number;
  collapsed?: boolean;
}) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [notes, setNotes] = useState<Note[]>([]);
  const [unread, setUnread] = useState(initialUnread);
  const [loading, setLoading] = useState(false);
  const [, startTransition] = useTransition();

  useEffect(() => setUnread(initialUnread), [initialUnread]);

  useEffect(() => {
    if (!open) return;
    setLoading(true);
    listNotifications()
      .then((rows) => setNotes(rows as unknown as Note[]))
      .catch(() => setNotes([]))
      .finally(() => setLoading(false));
  }, [open]);

  // Escape closes, and a click anywhere else does too — a panel that traps you
  // is worse than one that closes when you didn't mean it.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false);
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  function openNote(note: Note) {
    setOpen(false);
    startTransition(async () => {
      if (!note.readAt) {
        await markRead(note.id);
        setUnread((n) => Math.max(0, n - 1));
      }
      if (note.href) router.push(note.href);
    });
  }

  return (
    <div className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        aria-label={unread > 0 ? `Notifications (${unread} unread)` : "Notifications"}
        className={cn(
          "pressable relative flex h-8 items-center gap-2.5 rounded-md px-2 text-[13px] font-medium text-muted-foreground transition-colors hover:text-foreground",
          collapsed && "w-full justify-center px-0",
        )}
      >
        <Bell className="h-4 w-4 shrink-0" strokeWidth={2} />
        {!collapsed && <span>Notifications</span>}
        {unread > 0 && (
          <span
            className={cn(
              "rounded-full bg-foreground px-1.5 py-0.5 text-[11px] font-semibold tabular-nums text-background",
              collapsed
                ? "absolute right-1 top-0.5 px-1 py-0 text-[10px] leading-tight"
                : "ml-auto",
            )}
          >
            {unread > 99 ? "99+" : unread}
          </span>
        )}
      </button>

      <AnimatePresence>
        {open && (
          <>
            <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} aria-hidden />
            <motion.div
              initial={{ opacity: 0, scale: 0.97, y: 4 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.98 }}
              transition={{ type: "spring", bounce: 0, duration: 0.28 }}
              // Grows out of the bell rather than appearing from nowhere.
              style={{ transformOrigin: "bottom left" }}
              className="absolute bottom-full left-0 z-50 mb-2 w-[320px] overflow-hidden rounded-xl bg-card shadow-pop"
            >
              <div className="flex items-center justify-between border-b border-hairline px-3 py-2">
                <span className="text-[13px] font-semibold">Notifications</span>
                {unread > 0 && (
                  <button
                    onClick={() =>
                      startTransition(async () => {
                        await markAllRead();
                        setUnread(0);
                        setNotes((ns) => ns.map((n) => ({ ...n, readAt: new Date() })));
                      })
                    }
                    className="pressable text-[12px] text-muted-foreground hover:text-foreground"
                  >
                    Mark all read
                  </button>
                )}
              </div>

              <div className="max-h-[min(60vh,420px)] overflow-y-auto">
                {loading ? (
                  <p className="px-3 py-6 text-center text-[13px] text-muted-foreground">Loading…</p>
                ) : notes.length === 0 ? (
                  <div className="px-3 py-8 text-center">
                    <Check className="mx-auto mb-1.5 h-4 w-4 text-muted-foreground" />
                    <p className="text-[13px] font-medium">Nothing needs you</p>
                    <p className="mt-0.5 text-[12px] text-muted-foreground">
                      Due cards, tickets Claude files and unconfirmed proposals show up here.
                    </p>
                  </div>
                ) : (
                  notes.map((note) => (
                    <button
                      key={note.id}
                      onClick={() => openNote(note)}
                      className={cn(
                        "flex w-full gap-2.5 border-b border-hairline px-3 py-2.5 text-left transition-colors last:border-0 hover:bg-muted/50",
                        !note.readAt && "bg-muted/25",
                      )}
                    >
                      <span
                        className={cn(
                          "mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full",
                          note.readAt ? "bg-transparent" : "bg-foreground",
                        )}
                        aria-hidden
                      />
                      <span className="min-w-0 flex-1">
                        <span className="block text-[13px] font-medium leading-snug">
                          {note.title}
                        </span>
                        {note.body && (
                          <span className="mt-0.5 block line-clamp-2 text-[12px] leading-snug text-muted-foreground">
                            {note.body}
                          </span>
                        )}
                        <span className="mt-1 block text-[11px] text-muted-foreground/70">
                          {formatShortDate(note.createdAt)}
                        </span>
                      </span>
                    </button>
                  ))
                )}
              </div>

              <Link
                href="/settings/notifications"
                onClick={() => setOpen(false)}
                className="block border-t border-hairline px-3 py-2 text-center text-[12px] text-muted-foreground hover:text-foreground"
              >
                Notification settings
              </Link>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
